"""Initial migration

Revision ID: 8cb133106ff8
Revises: bb069c45e009
Create Date: 2026-01-15 10:37:25.523519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb133106ff8'
down_revision = 'bb069c45e009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturer_pin', schema=None) as batch_op:
        batch_op.drop_column('lecturer_email')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))

    with op.batch_alter_table('lecturer_pin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecturer_email', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
